spring.application.name=peliculasapi

spring.datasource.url=jdbc:postgresql://localhost:5432/peliculasdb
spring.datasource.username=postgres
spring.datasource.password=cusipuma

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html

server.port=8081